kNN Regression

1.Import dataset
2.Separet x,y
3.train,test
4.Apply linear regression
5.Evaluate model,Apply KNN regresion evaluate model 

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_excel("Height-Weight.xlsx")
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
df1= df.copy()
df2 = df.copy()
df3 = df.copy()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   object 
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), object(1)
memory usage: 200.6+ KB


In [5]:
df.shape

(8555, 3)

In [6]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [7]:
df.corr(numeric_only =True)

Height    Weight
Height  1.000000  0.922975
Weight  0.922975  1.000000

# Label Encoding

In [8]:
df.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [9]:
from pandas.core.dtypes.common import is_numeric_dtype
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

In [10]:
for col in df.columns:
    if is_numeric_dtype(df[col]):
        continue 
    else:
        df[col]= le.fit_transform(df[col])
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

# Scaling( value gula k ekta range e nia ase, by default 0-1

In [11]:
from sklearn.preprocessing import MinMaxScaler
mn = MinMaxScaler()

In [12]:
df["Height"]

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...    
8550    60.483946
8551    63.423372
8552    65.584057
8553    67.429971
8554    60.921791
Name: Height, Length: 8555, dtype: float64

In [13]:
df["Height"]= mn.fit_transform(df[["Height"]])
df.head()

Gender    Height      Weight
0       1  0.744399  241.893563
1       1  0.548328  162.310473
2       1  0.754583  212.740856
3       1  0.662487  220.042470
4       1  0.590905  206.349801

In [14]:
df["Weight"]= mn.fit_transform(df[["Weight"]])
df.head()

Gender    Height    Weight
0       1  0.744399  0.862415
1       1  0.548328  0.472703
2       1  0.754583  0.719657
3       1  0.662487  0.755412
4       1  0.590905  0.688360

# Separate x,y

In [15]:
x=df.drop("Weight", axis=1)
x.head()

Gender    Height
0       1  0.744399
1       1  0.548328
2       1  0.754583
3       1  0.662487
4       1  0.590905

In [16]:
y= df[["Weight"]]
y.head()

Weight
0  0.862415
1  0.472703
2  0.719657
3  0.755412
4  0.688360

# Train test split

In [17]:
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression

In [18]:
xtrain,xtest,ytrain,ytest =tts(x,y,test_size=0.3,random_state=78)


In [19]:
xtrain.head()

Gender    Height
2984       1  0.516626
6487       0  0.296121
7243       0  0.284884
6898       0  0.218997
6136       0  0.416769

In [20]:
xtrain.shape

(5988, 2)

# Applying Linear reggrassion

In [21]:
ln=LinearRegression()

In [22]:
ln.fit(xtrain,ytrain)

LinearRegression()

In [23]:
pred=ln.predict(xtest)
pred

array([[0.59624222],
       [0.3639663 ],
       [0.47552225],
       ...,
       [0.53065853],
       [0.29741744],
       [0.79028672]])

In [24]:
ln.predict([[0,0.356]])

array([[0.34609697]])

# Accuracy, MSE, MAE

In [25]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [26]:
accuracy = r2_score(ytest,pred)
accuracy

0.8999186031764108

In [27]:
mae =mean_absolute_error(ytest,pred)
mae

0.0396460799911652

In [28]:
mse =mean_squared_error(ytest,pred)
mse

0.0025196220667004685

# Visualization

In [29]:
#xtrain=xtrain.drop("Gender",axis =1)
#xtrain.head()

In [30]:
#plt.scatter(xtrain,ytrain)

# Applying KNN Reggression

In [31]:
from sklearn.neighbors import KNeighborsRegressor

In [32]:
ne=KNeighborsRegressor(n_neighbors=5)

In [33]:
ne.fit(xtrain,ytrain)

KNeighborsRegressor()

In [34]:
kntest=ne.predict(xtest)

In [35]:
kntest

array([[0.60597986],
       [0.40606008],
       [0.43789879],
       ...,
       [0.51945773],
       [0.28676611],
       [0.82506736]])

In [36]:
ne.predict([[0,0.356]])

array([[0.34625965]])

# Evaluate model

In [37]:
r2_score(ytest,kntest)

0.881850322291756

In [38]:
mse =mean_squared_error(ytest,kntest)

In [39]:
mse

0.0029745041993366156

In [40]:
mae=mean_absolute_error(ytest,kntest)
mae

0.04325848719725546